### PR TITLE
4 guess country functionality

### LINKED ISSUE #4: guess country functionality
guess country functionality

### PR DESCRIPTION
**Pull request by cchriss123**
First alpha version of map

### CODE REVIEW

**Comment by MikaelEdwartz** [comment]
Fy fucking helvete vad snygg kod

**Review by AntonLindskog96 — COMMENTED** [review]
LOOKS GOOD

**Review by AntonLindskog96 — APPROVED** [review]
LOOKS GOOD

**Review by cchriss123 — COMMENTED** [review]
hmm

**Review by MikaelEdwartz — APPROVED** [review]
looks not so good but i think ok

**Pull request merged**
